# Generated by Django 4.1 on 2023-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_alter_gallerymodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
