# Generated by Django 4.1 on 2023-07-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0003_alter_gallerymodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
